#!/usr/bin/python
import numpy as np
from PIL import Image, ImageDraw
IMAGE_SIZE=224

import sys
for f in sys.argv[1:]:
    fd = open(f, "r")
    buf = fd.read(IMAGE_SIZE*IMAGE_SIZE*2)
    arr = np.fromstring(buf, dtype=np.uint8).reshape([IMAGE_SIZE, IMAGE_SIZE, 2])
    z = np.zeros([IMAGE_SIZE, IMAGE_SIZE, 1], np.uint8)
    arr = np.append(arr, z, 2)
    img = Image.fromarray(arr, 'RGB')
    draw = ImageDraw.Draw(img)
    try:
        l = open(f.replace("Image", "Lbl").replace(".dat", ".txt"), "r")
        lbl = [float(s) for s in l.readline().split()]
        for i in range(0, len(lbl), 4):
             if lbl[i] != 0 and lbl[i+1] != 0:
                 xc = int(lbl[i]*IMAGE_SIZE)
                 yc = int(lbl[i+1]*IMAGE_SIZE)
                 xr = int(lbl[i+2]*IMAGE_SIZE)
                 yr = int(lbl[i+3]*IMAGE_SIZE)
                 draw.ellipse((xc-xr, yc-yr, xc+xr, yc+yr))
    except:
        pass

    del draw
    img.show()

     

